version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_demo
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mysql_demo
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demopass
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --performance-schema=ON
    restart: always
